//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTnew.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPTnew.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt password.
        /// </summary>
        public static string ButtonDecryptPwd {
            get {
                return ResourceManager.GetString("ButtonDecryptPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install 2015.
        /// </summary>
        public static string ButtonInstall2015 {
            get {
                return ResourceManager.GetString("ButtonInstall2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install &lt; 2015.
        /// </summary>
        public static string ButtonInstallMin2015 {
            get {
                return ResourceManager.GetString("ButtonInstallMin2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password &lt; 2015.
        /// </summary>
        public static string ButtonPasswordMin2015 {
            get {
                return ResourceManager.GetString("ButtonPasswordMin2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Export.
        /// </summary>
        public static string ButtonValidateExport {
            get {
                return ResourceManager.GetString("ButtonValidateExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Version.
        /// </summary>
        public static string ChangeVersion {
            get {
                return ResourceManager.GetString("ChangeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the TDViewerLight 2011 application..
        /// </summary>
        public static string Description2011TDViewerLight {
            get {
                return ResourceManager.GetString("Description2011TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2011 32bit..
        /// </summary>
        public static string Description2011ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Description2011ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2011 official version..
        /// </summary>
        public static string Description2011thinkPLM {
            get {
                return ResourceManager.GetString("Description2011thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities and plug-ins for version 2011..
        /// </summary>
        public static string Description2011Utilitytools {
            get {
                return ResourceManager.GetString("Description2011Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the TDViewerLight 2012 application..
        /// </summary>
        public static string Description2012TDViewerLight {
            get {
                return ResourceManager.GetString("Description2012TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2012 32bit..
        /// </summary>
        public static string Description2012ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Description2012ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2012 64bit..
        /// </summary>
        public static string Description2012ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Description2012ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2012 official version..
        /// </summary>
        public static string Description2012thinkPLM {
            get {
                return ResourceManager.GetString("Description2012thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities and plug-ins for version 2012..
        /// </summary>
        public static string Description2012Utilitytools {
            get {
                return ResourceManager.GetString("Description2012Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the TDViewerLight 2013 application..
        /// </summary>
        public static string Description2013TDViewerLight {
            get {
                return ResourceManager.GetString("Description2013TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2013 32bit..
        /// </summary>
        public static string Description2013ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Description2013ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2013 64bit..
        /// </summary>
        public static string Description2013ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Description2013ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2013 official version..
        /// </summary>
        public static string Description2013thinkPLM {
            get {
                return ResourceManager.GetString("Description2013thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities and plug-ins for version 2013..
        /// </summary>
        public static string Description2013Utilitytools {
            get {
                return ResourceManager.GetString("Description2013Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the TDViewerLight 2014 application..
        /// </summary>
        public static string Description2014TDViewerLight {
            get {
                return ResourceManager.GetString("Description2014TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2014 32bit..
        /// </summary>
        public static string Description2014ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Description2014ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2014 64bit..
        /// </summary>
        public static string Description2014ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Description2014ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2014 official version..
        /// </summary>
        public static string Description2014thinkPLM {
            get {
                return ResourceManager.GetString("Description2014thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities and plug-ins for version 2014..
        /// </summary>
        public static string Description2014Utilitytools {
            get {
                return ResourceManager.GetString("Description2014Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the TDViewerLight 2015 SP3 application..
        /// </summary>
        public static string Description2015TDViewerLightSP3 {
            get {
                return ResourceManager.GetString("Description2015TDViewerLightSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2 Legacy version for old systems..
        /// </summary>
        public static string Description2015ThinkDesign32bitSP2 {
            get {
                return ResourceManager.GetString("Description2015ThinkDesign32bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP3 Legacy version for old systems..
        /// </summary>
        public static string Description2015ThinkDesign32bitSP3 {
            get {
                return ResourceManager.GetString("Description2015ThinkDesign32bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This self extracting file will install the official ThinkDesign suite 2015 64bit SP2..
        /// </summary>
        public static string Description2015ThinkDesign64bitSP2 {
            get {
                return ResourceManager.GetString("Description2015ThinkDesign64bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended version..
        /// </summary>
        public static string Description2015ThinkDesign64bitSP3 {
            get {
                return ResourceManager.GetString("Description2015ThinkDesign64bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2015 SP2..
        /// </summary>
        public static string Description2015thinkPLMSP2 {
            get {
                return ResourceManager.GetString("Description2015thinkPLMSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2015 SP3 official version..
        /// </summary>
        public static string Description2015thinkPLMSP3 {
            get {
                return ResourceManager.GetString("Description2015thinkPLMSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Licensing Installer, utilities and plug-ins for version 2015..
        /// </summary>
        public static string Description2015Utilitytools {
            get {
                return ResourceManager.GetString("Description2015Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy beta version for old systems..
        /// </summary>
        public static string Description2016ThinkDesign32bitbeta {
            get {
                return ResourceManager.GetString("Description2016ThinkDesign32bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta version of ThinkDesign 2016..
        /// </summary>
        public static string Description2016ThinkDesign64bitbeta {
            get {
                return ResourceManager.GetString("Description2016ThinkDesign64bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section includes thinkPLM 2016 beta version..
        /// </summary>
        public static string Description2016thinkPLMbeta {
            get {
                return ResourceManager.GetString("Description2016thinkPLMbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2011.zip.
        /// </summary>
        public static string Download2011TDViewerLight {
            get {
                return ResourceManager.GetString("Download2011TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2011.1build410/Selfdvd_td_2011T1_b410.exe.
        /// </summary>
        public static string Download2011ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Download2011ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2011.1build410/Selfdvd_thinkplm_2011T1_b410.exe.
        /// </summary>
        public static string Download2011thinkPLM {
            get {
                return ResourceManager.GetString("Download2011thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2011.zip.
        /// </summary>
        public static string Download2011Utilitytools {
            get {
                return ResourceManager.GetString("Download2011Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2012.1build20312/SelfCD_tdviewer_2012T1_b20312.exe.
        /// </summary>
        public static string Download2012TDViewerLight {
            get {
                return ResourceManager.GetString("Download2012TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2012.1build20312/Selfdvd_td_2012T1_b20312.exe.
        /// </summary>
        public static string Download2012ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Download2012ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2012.1build20312/Selfdvd_td_64bit_2012T1_b20312.exe.
        /// </summary>
        public static string Download2012ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Download2012ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2012.1build20312/Selfdvd_thinkplm_2012T1_b20312.exe.
        /// </summary>
        public static string Download2012thinkPLM {
            get {
                return ResourceManager.GetString("Download2012thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2012.zip.
        /// </summary>
        public static string Download2012Utilitytools {
            get {
                return ResourceManager.GetString("Download2012Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2013.1build21029/SelfCD_tdviewer_2013T1_b21029.exe.
        /// </summary>
        public static string Download2013TDViewerLight {
            get {
                return ResourceManager.GetString("Download2013TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2013.1build21029/Selfdvd_td_2013T1_b21029.exe.
        /// </summary>
        public static string Download2013ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Download2013ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2013.1build21029/Selfdvd_td_64bit_2013T1_b21029.exe.
        /// </summary>
        public static string Download2013ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Download2013ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2013.1build21029/Selfdvd_thinkplm_2013T1_b21029.exe.
        /// </summary>
        public static string Download2013thinkPLM {
            get {
                return ResourceManager.GetString("Download2013thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2013.zip.
        /// </summary>
        public static string Download2013Utilitytools {
            get {
                return ResourceManager.GetString("Download2013Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2014.1build20506/SelfCD_tdviewer_2014T1_b20506.exe.
        /// </summary>
        public static string Download2014TDViewerLight {
            get {
                return ResourceManager.GetString("Download2014TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2014.1build20506/Selfdvd_td_2014T1_b20506.exe.
        /// </summary>
        public static string Download2014ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Download2014ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2014.1build20506/Selfdvd_td_64bit_2014T1_b20506.exe.
        /// </summary>
        public static string Download2014ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Download2014ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2014.1build20506/Selfdvd_thinkplm_2014T1_b20506.exe.
        /// </summary>
        public static string Download2014thinkPLM {
            get {
                return ResourceManager.GetString("Download2014thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2014.zip.
        /// </summary>
        public static string Download2014Utilitytools {
            get {
                return ResourceManager.GetString("Download2014Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30502/SelfCD_tdviewer_2015T2_b30502_64bit.exe.
        /// </summary>
        public static string Download2015TDViewerLightSP3 {
            get {
                return ResourceManager.GetString("Download2015TDViewerLightSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30125/Selfdvd_td_2015T2_b30125.exe.
        /// </summary>
        public static string Download2015ThinkDesign32bitSP2 {
            get {
                return ResourceManager.GetString("Download2015ThinkDesign32bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30502/Selfdvd_td_2015T2_b30502.exe.
        /// </summary>
        public static string Download2015ThinkDesign32bitSP3 {
            get {
                return ResourceManager.GetString("Download2015ThinkDesign32bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30125/Selfdvd_td_64bit_2015T2_b30125.exe.
        /// </summary>
        public static string Download2015ThinkDesign64bitSP2 {
            get {
                return ResourceManager.GetString("Download2015ThinkDesign64bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30502/Selfdvd_td_64bit_2015T2_b30502.exe.
        /// </summary>
        public static string Download2015ThinkDesign64bitSP3 {
            get {
                return ResourceManager.GetString("Download2015ThinkDesign64bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30125/Selfdvd_thinkplm_2015T2_b30125.exe.
        /// </summary>
        public static string Download2015thinkPLMSP2 {
            get {
                return ResourceManager.GetString("Download2015thinkPLMSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2015.2build30502/Selfdvd_thinkplm_2015T2_b30502.exe.
        /// </summary>
        public static string Download2015thinkPLMSP3 {
            get {
                return ResourceManager.GetString("Download2015thinkPLMSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3tools/Tools2015.zip.
        /// </summary>
        public static string Download2015Utilitytools {
            get {
                return ResourceManager.GetString("Download2015Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2016_build20712/dvd_td_2016T1_b20712.iso.
        /// </summary>
        public static string Download2016ThinkDesign32bitbeta {
            get {
                return ResourceManager.GetString("Download2016ThinkDesign32bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2016_build20712/dvd_td_64bit_2016T1_b20712.iso.
        /// </summary>
        public static string Download2016ThinkDesign64bitbeta {
            get {
                return ResourceManager.GetString("Download2016ThinkDesign64bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://t3user:t3user2012@ftp.think3.eu/t3software/2016_build20617/dvd_thinkplm_2016T1_b20617.iso.
        /// </summary>
        public static string Download2016thinkPLMbeta {
            get {
                return ResourceManager.GetString("Download2016thinkPLMbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpRange.
        /// </summary>
        public static string ExpRange {
            get {
                return ResourceManager.GetString("ExpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string infofiltered {
            get {
                return ResourceManager.GetString("infofiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string lengthmenu {
            get {
                return ResourceManager.GetString("lengthmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string LengthPassword {
            get {
                return ResourceManager.GetString("LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License ID.
        /// </summary>
        public static string LicenseId {
            get {
                return ResourceManager.GetString("LicenseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineID.
        /// </summary>
        public static string MachineID {
            get {
                return ResourceManager.GetString("MachineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MED.
        /// </summary>
        public static string MED {
            get {
                return ResourceManager.GetString("MED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a row to select it.
        /// </summary>
        public static string noRowsSelected {
            get {
                return ResourceManager.GetString("noRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDViewerLight 2011.
        /// </summary>
        public static string Product2011TDViewerLight {
            get {
                return ResourceManager.GetString("Product2011TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2011 32bit.
        /// </summary>
        public static string Product2011ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Product2011ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2011.
        /// </summary>
        public static string Product2011thinkPLM {
            get {
                return ResourceManager.GetString("Product2011thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility tools.
        /// </summary>
        public static string Product2011Utilitytools {
            get {
                return ResourceManager.GetString("Product2011Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDViewerLight 2012.
        /// </summary>
        public static string Product2012TDViewerLight {
            get {
                return ResourceManager.GetString("Product2012TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2012 32bit.
        /// </summary>
        public static string Product2012ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Product2012ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2012 64bit.
        /// </summary>
        public static string Product2012ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Product2012ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2012.
        /// </summary>
        public static string Product2012thinkPLM {
            get {
                return ResourceManager.GetString("Product2012thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility tools.
        /// </summary>
        public static string Product2012Utilitytools {
            get {
                return ResourceManager.GetString("Product2012Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDViewerLight 2013.
        /// </summary>
        public static string Product2013TDViewerLight {
            get {
                return ResourceManager.GetString("Product2013TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2013 32bit.
        /// </summary>
        public static string Product2013ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Product2013ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2013 64bit.
        /// </summary>
        public static string Product2013ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Product2013ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2013.
        /// </summary>
        public static string Product2013thinkPLM {
            get {
                return ResourceManager.GetString("Product2013thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility tools.
        /// </summary>
        public static string Product2013Utilitytools {
            get {
                return ResourceManager.GetString("Product2013Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDViewerLight 2014.
        /// </summary>
        public static string Product2014TDViewerLight {
            get {
                return ResourceManager.GetString("Product2014TDViewerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2014 32bit.
        /// </summary>
        public static string Product2014ThinkDesign32bit {
            get {
                return ResourceManager.GetString("Product2014ThinkDesign32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2014 64bit.
        /// </summary>
        public static string Product2014ThinkDesign64bit {
            get {
                return ResourceManager.GetString("Product2014ThinkDesign64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2014.
        /// </summary>
        public static string Product2014thinkPLM {
            get {
                return ResourceManager.GetString("Product2014thinkPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility tools.
        /// </summary>
        public static string Product2014Utilitytools {
            get {
                return ResourceManager.GetString("Product2014Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDViewerLight 2015 SP3.
        /// </summary>
        public static string Product2015TDViewerLightSP3 {
            get {
                return ResourceManager.GetString("Product2015TDViewerLightSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2015 32bit SP2.
        /// </summary>
        public static string Product2015ThinkDesign32bitSP2 {
            get {
                return ResourceManager.GetString("Product2015ThinkDesign32bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2015 32bit SP3.
        /// </summary>
        public static string Product2015ThinkDesign32bitSP3 {
            get {
                return ResourceManager.GetString("Product2015ThinkDesign32bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2015 64bit SP2.
        /// </summary>
        public static string Product2015ThinkDesign64bitSP2 {
            get {
                return ResourceManager.GetString("Product2015ThinkDesign64bitSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2015 64bit SP3.
        /// </summary>
        public static string Product2015ThinkDesign64bitSP3 {
            get {
                return ResourceManager.GetString("Product2015ThinkDesign64bitSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2015 SP2.
        /// </summary>
        public static string Product2015thinkPLMSP2 {
            get {
                return ResourceManager.GetString("Product2015thinkPLMSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2015 SP3.
        /// </summary>
        public static string Product2015thinkPLMSP3 {
            get {
                return ResourceManager.GetString("Product2015thinkPLMSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility tools &amp; Floating Licensing Installer.
        /// </summary>
        public static string Product2015Utilitytools {
            get {
                return ResourceManager.GetString("Product2015Utilitytools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2016 32bit beta.
        /// </summary>
        public static string Product2016ThinkDesign32bitbeta {
            get {
                return ResourceManager.GetString("Product2016ThinkDesign32bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2016 64bit beta.
        /// </summary>
        public static string Product2016ThinkDesign64bitbeta {
            get {
                return ResourceManager.GetString("Product2016ThinkDesign64bitbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thinkPLM 2016 beta.
        /// </summary>
        public static string Product2016thinkPLMbeta {
            get {
                return ResourceManager.GetString("Product2016thinkPLMbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string RequiredFieldPassword {
            get {
                return ResourceManager.GetString("RequiredFieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 row selected.
        /// </summary>
        public static string rowsSelected {
            get {
                return ResourceManager.GetString("rowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download here the beta version of the new release..
        /// </summary>
        public static string View_Download_Text1 {
            get {
                return ResourceManager.GetString("View_Download_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2016 beta (x64) - 1.86 GB.
        /// </summary>
        public static string View_Download_Text2 {
            get {
                return ResourceManager.GetString("View_Download_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking News.
        /// </summary>
        public static string View_Home_BreakingNews {
            get {
                return ResourceManager.GetString("View_Home_BreakingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Management.
        /// </summary>
        public static string View_Home_CaseManagement {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact our Customer Care and open a New Case..
        /// </summary>
        public static string View_Home_CaseManagement_Text1 {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your old credentials to access this section..
        /// </summary>
        public static string View_Home_CaseManagement_Text2 {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Learning.
        /// </summary>
        public static string View_Home_ELearning {
            get {
                return ResourceManager.GetString("View_Home_ELearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software training material, like video and step-by-step tutorials, supplied via the web..
        /// </summary>
        public static string View_Home_ELearning_Text {
            get {
                return ResourceManager.GetString("View_Home_ELearning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Licensing.
        /// </summary>
        public static string View_Home_NewLicensing {
            get {
                return ResourceManager.GetString("View_Home_NewLicensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All you need to know about C2V, V2C and Floating Licensing..
        /// </summary>
        public static string View_Home_NewLicensing_Text {
            get {
                return ResourceManager.GetString("View_Home_NewLicensing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.think3.eu/images/pdf/Licenses.pdf.
        /// </summary>
        public static string View_Home_NewLicensingLink {
            get {
                return ResourceManager.GetString("View_Home_NewLicensingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the new Customer Care portal!.
        /// </summary>
        public static string View_Home_Subtitle {
            get {
                return ResourceManager.GetString("View_Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2016 beta is now available! Have a look at the Download section..
        /// </summary>
        public static string View_Home_Text1 {
            get {
                return ResourceManager.GetString("View_Home_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try for free ThinkDesign 2015! Write to us to know more..
        /// </summary>
        public static string View_Home_Text2 {
            get {
                return ResourceManager.GetString("View_Home_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign Help.
        /// </summary>
        public static string View_Home_THelp {
            get {
                return ResourceManager.GetString("View_Home_THelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes &amp; Help manual 2016 - Work in Progress..
        /// </summary>
        public static string View_Home_THelp_Text {
            get {
                return ResourceManager.GetString("View_Home_THelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guidebook.
        /// </summary>
        public static string View_Home_UserGuidebook {
            get {
                return ResourceManager.GetString("View_Home_UserGuidebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can access the User Guidebook..
        /// </summary>
        public static string View_Home_UserGuidebook_Text {
            get {
                return ResourceManager.GetString("View_Home_UserGuidebook_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR Guidebook.
        /// </summary>
        public static string View_Home_VarGuidebook {
            get {
                return ResourceManager.GetString("View_Home_VarGuidebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can access the VAR Guidebook..
        /// </summary>
        public static string View_Home_VarGuidebook_Text {
            get {
                return ResourceManager.GetString("View_Home_VarGuidebook_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string View_HomeIndex_ChangePassword {
            get {
                return ResourceManager.GetString("View_HomeIndex_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string View_HomeIndex_Hello {
            get {
                return ResourceManager.GetString("View_HomeIndex_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string View_HomeIndex_Logoff {
            get {
                return ResourceManager.GetString("View_HomeIndex_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string View_HomeIndex_of {
            get {
                return ResourceManager.GetString("View_HomeIndex_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care.
        /// </summary>
        public static string View_HomeIndex_Title {
            get {
                return ResourceManager.GetString("View_HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string View_Menu_Activities {
            get {
                return ResourceManager.GetString("View_Menu_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Companies.
        /// </summary>
        public static string View_Menu_AllCompanies {
            get {
                return ResourceManager.GetString("View_Menu_AllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Licenses.
        /// </summary>
        public static string View_Menu_AllLicenses {
            get {
                return ResourceManager.GetString("View_Menu_AllLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All People.
        /// </summary>
        public static string View_Menu_AllPeoples {
            get {
                return ResourceManager.GetString("View_Menu_AllPeoples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string View_Menu_Download {
            get {
                return ResourceManager.GetString("View_Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string View_Menu_Home {
            get {
                return ResourceManager.GetString("View_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string View_Menu_Licenses {
            get {
                return ResourceManager.GetString("View_Menu_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string View_Menu_Orders {
            get {
                return ResourceManager.GetString("View_Menu_Orders", resourceCulture);
            }
        }
    }
}
