//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTnew.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPTnew.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string LengthPassword {
            get {
                return ResourceManager.GetString("LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string RequiredFieldPassword {
            get {
                return ResourceManager.GetString("RequiredFieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking News.
        /// </summary>
        public static string View_Home_BreakingNews {
            get {
                return ResourceManager.GetString("View_Home_BreakingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Management.
        /// </summary>
        public static string View_Home_CaseManagement {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact our Customer Care and open a New Case..
        /// </summary>
        public static string View_Home_CaseManagement_Text1 {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your old credentials to access this section..
        /// </summary>
        public static string View_Home_CaseManagement_Text2 {
            get {
                return ResourceManager.GetString("View_Home_CaseManagement_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Learning.
        /// </summary>
        public static string View_Home_ELearning {
            get {
                return ResourceManager.GetString("View_Home_ELearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software training material, like video and step-by-step tutorials, supplied via the web..
        /// </summary>
        public static string View_Home_ELearning_Text {
            get {
                return ResourceManager.GetString("View_Home_ELearning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Licensing.
        /// </summary>
        public static string View_Home_NewLicensing {
            get {
                return ResourceManager.GetString("View_Home_NewLicensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All you need to know about C2V, V2C and Floating Licensing..
        /// </summary>
        public static string View_Home_NewLicensing_Text {
            get {
                return ResourceManager.GetString("View_Home_NewLicensing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the new Customer Care portal!.
        /// </summary>
        public static string View_Home_Subtitle {
            get {
                return ResourceManager.GetString("View_Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign 2016 beta is now available! Have a look at the Download section..
        /// </summary>
        public static string View_Home_Text1 {
            get {
                return ResourceManager.GetString("View_Home_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try for free ThinkDesign 2015! Write to us to know more..
        /// </summary>
        public static string View_Home_Text2 {
            get {
                return ResourceManager.GetString("View_Home_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkDesign Help.
        /// </summary>
        public static string View_Home_THelp {
            get {
                return ResourceManager.GetString("View_Home_THelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes &amp; Help manual 2016 - Work in Progress..
        /// </summary>
        public static string View_Home_THelp_Text {
            get {
                return ResourceManager.GetString("View_Home_THelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guidebook.
        /// </summary>
        public static string View_Home_UserGuidebook {
            get {
                return ResourceManager.GetString("View_Home_UserGuidebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can access the User Guidebook..
        /// </summary>
        public static string View_Home_UserGuidebook_Text {
            get {
                return ResourceManager.GetString("View_Home_UserGuidebook_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR Guidebook.
        /// </summary>
        public static string View_Home_VarGuidebook {
            get {
                return ResourceManager.GetString("View_Home_VarGuidebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can access the VAR Guidebook..
        /// </summary>
        public static string View_Home_VarGuidebook_Text {
            get {
                return ResourceManager.GetString("View_Home_VarGuidebook_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string View_HomeIndex_ChangePassword {
            get {
                return ResourceManager.GetString("View_HomeIndex_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string View_HomeIndex_Hello {
            get {
                return ResourceManager.GetString("View_HomeIndex_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string View_HomeIndex_Logoff {
            get {
                return ResourceManager.GetString("View_HomeIndex_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string View_HomeIndex_of {
            get {
                return ResourceManager.GetString("View_HomeIndex_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care.
        /// </summary>
        public static string View_HomeIndex_Title {
            get {
                return ResourceManager.GetString("View_HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string View_Menu_Activities {
            get {
                return ResourceManager.GetString("View_Menu_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Companies.
        /// </summary>
        public static string View_Menu_AllCompanies {
            get {
                return ResourceManager.GetString("View_Menu_AllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Licenses.
        /// </summary>
        public static string View_Menu_AllLicenses {
            get {
                return ResourceManager.GetString("View_Menu_AllLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All People.
        /// </summary>
        public static string View_Menu_AllPeoples {
            get {
                return ResourceManager.GetString("View_Menu_AllPeoples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string View_Menu_Download {
            get {
                return ResourceManager.GetString("View_Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string View_Menu_Home {
            get {
                return ResourceManager.GetString("View_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string View_Menu_Licenses {
            get {
                return ResourceManager.GetString("View_Menu_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string View_Menu_Orders {
            get {
                return ResourceManager.GetString("View_Menu_Orders", resourceCulture);
            }
        }
    }
}
